gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#00baff"
      - "bold"
    inactiveBorderColor:
      - "#061B2B"
    searchingActiveBorderColor:
      - "#00c6e1"
      - "bold"
    optionsTextColor:
      - "#178FFF"
    selectedLineBgColor:
      - "#0F2E3F"
    cherryPickedCommitFgColor:
      - "#FFDF6E"
    cherryPickedCommitBgColor:
      - "#7A5CFF"
    markedBaseCommitFgColor:
      - "#00c6e1"
    markedBaseCommitBgColor:
      - "#00c6e1"
    unstagedChangesColor:
      - "#FF6E8A"
    defaultFgColor:
      - "#B4C9FF"
