[[mgr.prepend_keymap]]
on = ["<"]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"

[[mgr.prepend_keymap]]
on = "<C-x>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[mgr.prepend_keymap]]
on = ["u", "t", "a"]
run = "plugin mactag add"
desc = "Tag selected files"

[[mgr.prepend_keymap]]
on = ["u", "t", "r"]
run = "plugin mactag remove"
desc = "Untag selected files"

[[mgr.prepend_keymap]]
on = ["<C-c>"]
run = "plugin close-and-restore-tab close_to_left"
desc = "Close the current tab and turn to right tab, or quit if it is last tab"

[[mgr.prepend_keymap]]
on = ["<C-t>"]
run = "plugin close-and-restore-tab restore"
desc = "Restore the closed tab"

[[mgr.prepend_keymap]]
# First Non-directory
on = ["g", "f", "f"]
run = "plugin first-non-directory"
desc = "Jumps to the first file"

[[mgr.prepend_keymap]]
# Chmod on howered files
on = ["m", "c"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
# Yamb (bookmarks)
on = ["b", "a"]
run = "plugin yamb save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = ["b", "g"]
run = "plugin yamb jump_by_key"
desc = "Jump bookmark"

[[mgr.prepend_keymap]]
on = ["b", "d"]
run = "plugin yamb delete_by_key"
desc = "Delete bookmark"

[[mgr.prepend_keymap]]
on = ["b", "D"]
run = "plugin yamb delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = ["b", "r"]
run = "plugin yamb rename_by_key"
desc = "Rename bookmark"

[[mgr.prepend_keymap]]
# Sudo 
on = ["R", "p", "p"]
run = "plugin sudo -- paste"
desc = "sudo paste"

[[mgr.prepend_keymap]]
on = ["R", "P"]
run = "plugin sudo -- paste --force"
desc = "sudo paste"

[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin sudo -- rename"
desc = "sudo rename"

[[mgr.prepend_keymap]]
on = ["R", "p", "l"]
run = "plugin sudo -- link"
desc = "sudo link"

[[mgr.prepend_keymap]]
on = ["R", "p", "r"]
run = "plugin sudo -- link --relative"
desc = "sudo link relative path"

[[mgr.prepend_keymap]]
on = ["R", "p", "L"]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"

[[mgr.prepend_keymap]]
on = ["R", "a"]
run = "plugin sudo -- create"
desc = "sudo create"

[[mgr.prepend_keymap]]
on = ["R", "d"]
run = "plugin sudo -- remove"
desc = "sudo trash"

[[mgr.prepend_keymap]]
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = "plugin system-clipboard"

####################################################
#############      Navgigation      ################
####################################################

# Goto:

[[mgr.prepend_keymap]]
on = ["g", "<Space>"]
run = "cd --interactive"
desc = "Jump interactively"

[[mgr.prepend_keymap]]
on = ["g", "f", "l"]
run = "follow"
desc = "Follow hovered symlink"

[[mgr.prepend_keymap]]
on = ["g", "/"]
run = "cd /"
desc = "Goto Root"

[[mgr.prepend_keymap]]
on = ["g", "h"]
run = "cd $HOME"
desc = "Goto Home"

[[mgr.prepend_keymap]]
on = ["g", "t"]
run = "cd ~/.Trash"
desc = "Goto Trash"

[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/.config"
desc = "Goto Config Files"

[[mgr.prepend_keymap]]
on = ["g", "e"]
run = "cd ~/Desktop"
desc = "Goto Desktop"

[[mgr.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/Documents"
desc = "Goto Documents"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = "cd ~/res"
desc = "Goto Resources"

[[mgr.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/Downloads"
desc = "Goto Downloads"

[[mgr.prepend_keymap]]
on = ["g", "x"]
run = "cd ~/XML"
desc = "Goto XML"

[[mgr.prepend_keymap]]
on = ["g", "l"]
run = "cd ~/.local"
desc = "Goto Local Config"

[[mgr.prepend_keymap]]
on = ["g", "d", "p"]
run = "cd ~/Documents/Personal"
desc = "Goto personal docs"

[[mgr.prepend_keymap]]
on = ["g", "d", "t"]
run = "cd ~/Documents/TestAcc-bx"
desc = "Goto test account"

[[mgr.prepend_keymap]]
on = ["g", "d", "o"]
run = "cd ~/Documents/Obsidian"
desc = "Goto Obsidian storage"

[[mgr.prepend_keymap]]
on = ["g", "d", "c"]
run = "cd ~/Dotfiles"
desc = "Goto Dotfiles"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd ~/Music"
desc = "Goto Music"

####################################################
#############      Yazi UI      ####################
####################################################

# Lazygit
[[mgr.prepend_keymap]]
on = ["u", "g"]
run = "plugin lazygit"
desc = "run lazygit"

# Trash Restore
[[mgr.prepend_keymap]]
on = ["u", "t", "f"]
run = "plugin restore"
desc = "Restore last deleted files/folders"

[[mgr.prepend_keymap]]
on = ["u", "t", "i"]
run = "shell --block -- clear && trash-restore"
desc = "Restore deleted file (Interactive)"

# TODO: run = "shell --block -- clear && trash-restore --overwrite" --> merge instead of overwrite?

# Toggle Pane
[[mgr.prepend_keymap]]
on = ["u", "p"]
run = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"
